#!/usr/bin/env python3
"""10 — Figures and the paper-facing report (v3 Phase 5 + 6).

Generates every figure from saved results (no model needed) and writes
out/report/RESULTS.md containing:

* the §4.8 spine table (lead result, per v3: Section 7 leads with it)
* the §4.9 qualitative differentiation table vs BAGEL and Luna-2 (required
  for Related Work, with the citations filled in)
* the half-split table + the KEY success-criteria check
* the narrowed novelty claim (v3 boxed text) ready to drop into the
  Introduction
* the limitations list

Run:  python 10_figures_report.py
"""
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, ".")
from config import load_config, ATTACK_TYPES
from multi_harm_common import figures as F
from multi_harm_common.io_utils import load_json, save_json
from multi_harm_common.metrics import roc_points
from multi_harm_common.sigcache import load_cache

TYPES = ATTACK_TYPES


def main():
    cfg = load_config()
    figdir = os.path.join(cfg.out_dir, "figures")
    repdir = os.path.join(cfg.out_dir, "report")
    exp = os.path.join(cfg.out_dir, "experiments")
    os.makedirs(repdir, exist_ok=True)

    specs = load_json(os.path.join(cfg.out_dir, "calib", "specialists.json"))
    gen = load_json(os.path.join(cfg.out_dir, "calib", "general.json"))
    row1 = load_json(os.path.join(exp, "row1_attn_shared.json"))
    row2 = load_json(os.path.join(exp, "row2_general.json"))
    hid_base = load_json(os.path.join(exp, "baseline_hidden_only.json"))
    t48 = load_json(os.path.join(exp, "table_48.json"))
    tableA = load_json(os.path.join(exp, "tableA_main.json"))
    te = load_json(os.path.join(exp, "tableE_unseen.json"), default={})
    lat = load_json(os.path.join(exp, "latency.json"), default={})
    qc = load_json(os.path.join(exp, "quant_compare.json"), default={})
    records = pd.read_csv(os.path.join(exp, "test_records.csv"))

    # ------------------------------------------------------------------ figs
    print("Writing figures ...")
    F.fig_halves_per_specialist(
        [specs[t] for t in TYPES] + [gen], figdir)
    F.fig_48_configs(t48, figdir)

    # ROCs on test (fused scores)
    cache = load_cache(cfg.data_dir)
    df = pd.read_parquet(os.path.join(cfg.data_dir, "dataset.parquet"))
    curves = {}
    from multi_harm_common.detect import score_spec_on_split
    for t in TYPES:
        ev = score_spec_on_split(specs[t], df, cache, "test", cfg.epsilon)
        m = (ev["types"] == t) | (ev["labels"] == 0)
        f, tt = roc_points(ev["labels"][m], ev["s"][m])
        curves[t] = (f, tt)
    evg = score_spec_on_split(gen, df, cache, "test", cfg.epsilon)
    curves["general"] = roc_points(evg["labels"], evg["s"])
    F.fig_rocs(curves, figdir)
    F.fig_confusion(records.to_dict("records"), figdir)
    qc2 = dict(qc)
    L_star = gen["L_star"]
    qc2["chosen_L"] = L_star
    F.fig_quant_compare(qc2, figdir)
    F.fig_latency(lat, figdir)
    F.fig_scores_hist(records, figdir)
    print("  done.")

    # ------------------------------------------------------------- report
    mean_gain = float(np.mean([
        t48["fused per-attack specialized (row 3)"][t]
        - t48["fused shared HARM_general (4.8 r2)"][t] for t in TYPES]))
    cos_at_L = qc.get("per_layer_cos", {}).get(str(L_star))
    pairs = load_json(os.path.join(exp, "sec43_pearson_val.json"), default=None)

    md = []
    md.append("# Multi-HARM — Results Report\n")
    md.append("> Generated by 10_figures_report.py from out/ artifacts. "
              "All numbers below are from the TEST split unless stated.\n")

    md.append("\n## Lead result — §4.8 (attention generalization vs fusion "
              "specialization)\n")
    md.append("| Signal config | " + " | ".join(TYPES) + " | Spread |")
    md.append("|---|" + "---|" * (len(TYPES) + 1))
    for k, v in t48.items():
        md.append(f"| {k} | " + " | ".join(f"{v[t]:.4f}" for t in TYPES)
                  + f" | {v['spread']:.4f} |")
    md.append(f"\nFused-specialized gain over fused-shared (mean): **{mean_gain:+.4f}** "
              f"(v3 primary criterion: > 0.03).\n")

    md.append("\n## §4.9 — Qualitative differentiation (Related Work table)\n")
    md.append("| System | Detector type per specialist | Efficiency mechanism | "
              "Attribution mechanism | Attack types covered |")
    md.append("|---|---|---|---|---|")
    md.append("| BAGEL (Bootstrap AGgregated Ensemble Layer) | Fine-tuned small "
              "classifiers per attack type | Random-forest router + stochastic "
              "ensemble sampling | Router's structural features | Incremental, "
              "updatable |")
    md.append("| Galileo Luna-2 (production) | Not disclosed (proprietary) | Not "
              "disclosed | Trained classification output | 5 named categories |")
    md.append("| **Multi-HARM (this work)** | Attention-routing + residual-stream "
              "fusion probe on the SAME base model | Single shared forward pass; "
              "each specialist adds only a dot-product score | Argmax over "
              "specialist scores already computed for detection (no extra head) | "
              "4 fixed types + general fallback |")
    md.append("\nCitations to attach to this table: Hung et al. (*Attention "
              "Tracker*, 2024/2025); Zou et al. (*PIShield*, 2025); BAGEL; "
              "Galileo *Luna-2*; *UniGuardian*; *TaskTracker* (cited by "
              "PIShield as related). Fill exact venue/links before submission.\n")

    md.append("\n## Main results (Table A)\n")
    md.append(f"detection={tableA['detection']:.4f}  ASR={tableA['asr']:.4f}  "
              f"FPR={tableA['fpr']:.4f}  F1={tableA['f1']:.4f}  "
              f"mean-ASR={tableA['mean_asr']:.4f}")
    md.append("\n| Type | n | detection | ASR |")
    md.append("|---|---|---|---|")
    for t, v in tableA["per_type"].items():
        md.append(f"| {t} | {v['n']} | {v['detection']:.4f} | {v['asr']:.4f} |")

    md.append("\n## Attribution (Table D)\n")
    md.append(f"accuracy on detected injected samples: **{tableA['attr_accuracy']}**")
    if tableA["attr_confusion"]:
        md.append("\n| true | attributed | n |")
        md.append("|---|---|---|")
        for c in tableA["attr_confusion"]:
            md.append(f"| {c['attack_type']} | {c['attribution']} | {c['n']} |")

    md.append("\n## Half-split (v3 Phase 3 addition)\n")
    md.append("| specialist | L* | head | alpha | att-half AUROC | hid-half AUROC "
              "| fused AUROC |")
    md.append("|---|---|---|---|---|---|---|")
    for sp in [gen] + [specs[t] for t in TYPES]:
        a = sp["auroc"]
        md.append(f"| {sp['name']} | {sp['L_star']} | ({sp['head'][0]},"
                  f"{sp['head'][1]}) | {sp['alpha']:.2f} | {a['att_head']:.4f} "
                  f"| {a['hid']:.4f} | {a['fused']:.4f} |")

    md.append("\n## Success criteria (v3 KEY SUCCESS CRITERIA)\n")
    md.append("| Metric | Target | Actual | Status |")
    md.append("|---|---|---|---|")
    crit = lambda ok: "MET" if ok else "NOT MET"
    md.append(f"| Multi-HARM mean ASR | < 8% | {tableA['mean_asr']:.4f} | "
              f"{crit(tableA['mean_asr'] < 0.08)} |")
    md.append(f"| §4.8 specialized-vs-shared gain | > 3 pts | {mean_gain:.4f} | "
              f"{crit(mean_gain > 0.03)} |")
    md.append(f"| Mean FPR | < 5% | {tableA['fpr']:.4f} | "
              f"{crit(tableA['fpr'] < 0.05)} |")
    attr_acc = tableA.get("attr_accuracy")
    md.append(f"| Attribution accuracy | > 75% | "
              f"{attr_acc if attr_acc is not None else 'n/a'} | "
              f"{crit(attr_acc is not None and attr_acc > 0.75)} |")
    lat_pct = lat.get("forward_overhead_pct", lat.get("overhead_pct"))
    md.append(f"| Latency overhead | < 0.5% | "
              f"{lat_pct if lat_pct is None else format(lat_pct, '.3f') + ' %'} | "
              f"{crit(lat_pct is not None and lat_pct < 0.5)} |")
    md.append(f"| Unseen attack (§4.5) | within 10 pts of seen | "
              f"{te.get('asr_unseen')} vs {te.get('mean_asr_seen')} | "
              f"{crit(te.get('within_10_points'))} |")
    if qc.get("applicable"):
        md.append(f"| fp-ref vs 4-bit corr @ L*={L_star} | > 0.9 | {cos_at_L} | "
                  f"{crit(cos_at_L is not None and cos_at_L > 0.9)} |")
    else:
        md.append("| fp-ref vs 4-bit corr @ L* | > 0.9 | n/a (device) | n/a |")

    md.append("\n## Novelty claim (v3 boxed text — adjust to final numbers)\n")
    md.append("> To the best of our knowledge, this is the first work to (1) fuse "
              "attention-routing and residual-stream signals into a single "
              "detector score, (2) specialize that fused detector per attack type "
              "using independently calibrated fusion weights and thresholds while "
              "sharing one forward pass, and (3) derive attack-type attribution "
              "directly from which specialist's score dominates, without training "
              "a separate classification head. We position this relative to BAGEL "
              "(ensemble-of-specialists structure, different detector family) and "
              "Luna-2 (attribution as output, different mechanism), and we "
              "explicitly test whether specialization is necessary given "
              "Attention Tracker's reported cross-attack generalization of its "
              "single signal.\n")

    md.append("## Limitations (v2's six, reconstructed + v3's item 7)\n")
    md.append("1. **Quantization condition.** Main results run at 4-bit (nf4) for "
              "deployment cost; §2.3 reports the fp-ref vs 4-bit signal "
              "correlation (see figure). At L*="
              f"{L_star} the per-layer cosine is {cos_at_L}.")
    md.append("2. **Attack template coverage.** The four attack types and five "
              "goals are template-based; adaptive attacks (e.g. PISmith-style "
              "optimization) are NOT tested — no robustness claim is made.")
    md.append("3. **Single-domain source text.** Clean pairs come from MS-MARCO "
              "(short factual passages); behavior on longer/structured contexts "
              "is untested.")
    md.append("4. **Calibration budget.** Specialization uses ~150-200 calibration "
              "samples per specialist; how the gains scale with calibration size "
              "is not characterized.")
    md.append("5. **Model family.** Primary results use one 8B instruction model; "
              "cross-model transfer (Mistral-7B, Qwen2.5-7B) is in the Phase-1 "
              "plan but reported separately when run.")
    md.append("6. **Meta threshold tuning.** The global_max alternative threshold "
              "is tuned on val; the default per_spec mode uses calibration-only "
              "thresholds.")
    md.append("7. **Attention-signal generalization.** Attention Tracker reports "
              "its signal generalizes across attack types with one shared "
              f"calibration; our §4.8 results show row-1 spread = "
              f"{row1['spread']:.4f} and specialized-vs-shared fused gain = "
              f"{mean_gain:+.4f} — [state plainly after final numbers: whether "
              "specialization gains are modest or material].\n")

    md.append("## Figures\n")
    for fn in sorted(os.listdir(figdir)):
        md.append(f"- `{fn}`")

    with open(os.path.join(repdir, "RESULTS.md"), "w") as f:
        f.write("\n".join(md))
    print(f"\nReport written -> {os.path.join(repdir, 'RESULTS.md')}")


if __name__ == "__main__":
    main()
