#!/usr/bin/env python3
"""11 — Reproducibility package (v3 Phase 7).

Snapshots everything a reviewer (or your future self) needs to re-run the
project: environment, config, code hashes, dataset statistics, and a zip of
code + results (excluding the ~300 MB signal cache, with exact regeneration
steps instead).

Writes out/repro/REPRODUCIBILITY.md and out/repro/multi_harm_repro.zip
"""
import hashlib
import os
import shutil
import subprocess
import sys

import pandas as pd

sys.path.insert(0, ".")
from config import load_config
from multi_harm_common import env as ENV
from multi_harm_common.io_utils import load_json, save_json, ensure_dir


def sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    cfg = load_config()
    repdir = os.path.join(cfg.out_dir, "repro")
    ensure_dir(repdir)

    env = ENV.gpu_summary()
    lines = [f"# Multi-HARM v{cfg.version} — Reproducibility Package\n"]
    lines.append("## Provenance\n")
    lines.append(f"- config.version: {cfg.version}")
    lines.append(f"- base spec/baseline: {cfg.base_spec}")
    for cmd in (["git", "rev-parse", "--abbrev-ref", "HEAD"],
                ["git", "rev-parse", "--short", "HEAD"],
                ["git", "merge-base", "--is-ancestor", "base-v3", "HEAD"]):
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=20)
            if r.returncode == 0 and r.stdout.strip():
                lines.append(f"- `{' '.join(cmd[1:])}`: {r.stdout.strip()}")
        except Exception:
            pass
    lines.append("- base version tag `base-v3` = the unmodified v3.0 "
                 "implementation; every difference from it is listed in "
                 "CHANGELOG.md\n")
    lines.append("## Environment\n")
    for k, v in env.items():
        lines.append(f"- {k}: {v}")
    try:
        pip = subprocess.run([sys.executable, "-m", "pip", "freeze"],
                             capture_output=True, text=True, timeout=60)
        lines.append("\n### pip freeze\n```\n" + pip.stdout.strip()[:8000] + "\n```\n")
    except Exception as e:
        lines.append(f"(pip freeze failed: {e})\n")

    lines.append("\n## Config (effective)\n")
    cfgd = cfg.to_dict()
    save_json(cfgd, os.path.join(repdir, "config.json"))
    for k, v in cfgd.items():
        lines.append(f"- {k}: {v}")

    lines.append("\n## Code hashes (SHA-256)\n")
    lines.append("| file | sha256 |")
    lines.append("|---|---|")
    codefiles = sorted(f for f in os.listdir(".") if f.endswith(".py")) + \
        [f"multi_harm_common/{f}" for f in
         sorted(os.listdir("multi_harm_common")) if f.endswith(".py")]
    code_hash = {}
    for f in codefiles:
        code_hash[f] = sha256(f)
        lines.append(f"| {f} | {code_hash[f][:16]}... |")

    lines.append("\n## Dataset\n")
    dpath = os.path.join(cfg.data_dir, "dataset.parquet")
    if os.path.exists(dpath):
        df = pd.read_parquet(dpath)
        lines.append(f"- rows: {len(df)}")
        lines.append(f"- dataset.parquet sha256: {sha256(dpath)[:16]}...")
        lines.append("\n| attack_type | goal | train | val | test |")
        lines.append("|---|---|---|---|---|")
        ct = pd.crosstab([df["attack_type"], df["goal"]], df["split"])
        for (at, gl), r in ct.iterrows():
            lines.append(f"| {at} | {gl} | {r.get('train', 0)} | {r.get('val', 0)} "
                         f"| {r.get('test', 0)} |")
        cp = os.path.join(cfg.data_dir, "clean_pairs.parquet")
        if os.path.exists(cp):
            lines.append(f"\n- clean_pairs.parquet sha256: {sha256(cp)[:16]}...")

    lines.append("\n## Artifacts\n")
    for root, _, files in os.walk(cfg.out_dir):
        if "repro" in root:
            continue
        for f in sorted(files):
            p = os.path.join(root, f)
            lines.append(f"- {p} ({os.path.getsize(p) / 1e6:.2f} MB)")

    lines.append("\n## Regeneration steps\n")
    lines.append("""```bash
pip install -r requirements.txt
python 01_setup_and_validate.py            # env + model + shape smoke test
python 02_build_dataset.py                 # data/dataset.parquet
python 03_extract_signals.py --quant-compare   # §2.3 (before full extraction)
python 03_extract_signals.py               # §2.0 gate + full signal cache
python 04_calibrate_hstar.py               # pooled H*
python 05_baseline_attn_tracker.py         # §4.8 row 1
python 06_calibrate_general.py             # §4.8 row 2 + hidden-only baseline
python 07_calibrate_specialists.py         # 4 specialists + half-split table
python 08_meta_decision.py                 # meta layer on val
python 09_experiments_analysis.py --with-model   # all tables
python 10_figures_report.py                # figures + RESULTS.md
```
The signal cache (data/signals/, ~300 MB for the full run) is NOT included in
the zip; it is regenerated by `03_extract_signals.py` (~2-5 h on a T4,
resumable via out/progress/extract.json).
""")

    # ---- machine-readable manifest -----------------------------------------
    # REPRODUCIBILITY.md is for humans; this is for a reviewer who wants to check
    # that the numbers they are reading came from the code they are looking at,
    # and from the signal cache that cache actually claims to be.
    artifacts = {}
    for root, dirs, fns in os.walk(cfg.out_dir):
        dirs[:] = [d for d in dirs if d not in ("repro", "_stage")]
        for fn in fns:
            fp = os.path.join(root, fn)
            artifacts[os.path.relpath(fp, cfg.out_dir)] = sha256(fp)
    git = {}
    for key, cmd in (("branch", ["git", "rev-parse", "--abbrev-ref", "HEAD"]),
                     ("commit", ["git", "rev-parse", "HEAD"]),
                     ("base_v3_is_ancestor",
                      ["git", "merge-base", "--is-ancestor", "base-v3", "HEAD"])):
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=20)
            git[key] = (r.stdout.strip() if key != "base_v3_is_ancestor"
                        else r.returncode == 0) or None
        except Exception as e:
            git[key] = f"unavailable: {type(e).__name__}"
    if git.get("commit"):
        print(f"  provenance: {git.get('branch')}@{git['commit'][:12]}"
              + (" (dirty tree — the commit alone does not describe this run)"
                 if os.popen("git status --porcelain").read().strip() else ""))
    prov_path = os.path.join(cfg.data_dir, "signals", "sigcache_meta.json")
    prov = load_json(prov_path, default=None)
    if prov is None:
        print("  WARNING: no data/signals/sigcache_meta.json — how the cache was "
              "built (model, quant, row/skip counts) is unrecorded; re-run 03 to "
              "get it")
    manifest = {
        "git": git,
        "config": cfgd,
        "n_code_files": len(code_hash),
        "code_sha256": code_hash,
        "n_artifacts": len(artifacts),
        "artifact_sha256": dict(sorted(artifacts.items())),
        "signals_provenance": prov,
    }
    mpath = os.path.join(repdir, "repro_manifest.json")
    save_json(manifest, mpath)
    print(f"  manifest: {mpath} ({len(artifacts)} artifacts hashed)")
    lines.append("\n## Manifest\n")
    lines.append(f"- `repro_manifest.json` (also copied to the zip root): git "
                 f"{manifest['git'].get('branch')}@{str(manifest['git'].get('commit'))[:12]}, "
                 f"SHA-256 of every code file and of {len(artifacts)} out/ artifacts, "
                 f"plus the signal cache's provenance record")
    lines.append("- `data/signals/sigcache_meta.json` (copied into the zip): model, "
                 "quantization, row and skip counts the cache was built with — "
                 "compare it against your own before trusting a reused cache"
                 if prov is not None else
                 "- no `data/signals/sigcache_meta.json`: this cache's provenance "
                 "is unrecorded (re-run 03 with the current code to get it)")

    with open(os.path.join(repdir, "REPRODUCIBILITY.md"), "w") as f:
        f.write("\n".join(lines))

    # ---- zip: code + out/ + dataset metadata (excl. signal cache) ----------
    zpath = os.path.join(repdir, "multi_harm_repro.zip")
    if os.path.exists(zpath):
        os.remove(zpath)
    staging = os.path.join(repdir, "_stage")
    if os.path.exists(staging):
        shutil.rmtree(staging)
    os.makedirs(os.path.join(staging, "multi_harm_common"))
    for f in codefiles + ["requirements.txt", "README.md", "config.py",
                          "CHANGELOG.md", "DEMO_RUNBOOK.md"]:
        if os.path.exists(f) and f not in codefiles:
            shutil.copy(f, staging)
    for f in os.listdir("multi_harm_common"):
        if f.endswith(".py"):
            shutil.copy(os.path.join("multi_harm_common", f),
                        os.path.join(staging, "multi_harm_common"))
    shutil.copytree(cfg.out_dir, os.path.join(staging, "out"),
                    ignore=shutil.ignore_patterns("repro", "_stage"))
    # out/repro is excluded by the copytree ignore, so the manifest rides at the
    # archive root as well
    shutil.copy(mpath, os.path.join(staging, "repro_manifest.json"))
    if os.path.exists(os.path.join(cfg.data_dir, "dataset.parquet")):
        os.makedirs(os.path.join(staging, "data"))
        shutil.copy(os.path.join(cfg.data_dir, "dataset.parquet"),
                    os.path.join(staging, "data"))
    if prov is not None:
        os.makedirs(os.path.join(staging, "data", "signals"), exist_ok=True)
        shutil.copy(prov_path, os.path.join(staging, "data", "signals",
                                            "sigcache_meta.json"))
    shutil.make_archive(os.path.join(repdir, "multi_harm_repro"), "zip",
                        root_dir=staging)
    shutil.rmtree(staging)
    print(f"\nReproducibility package:\n  {os.path.join(repdir, 'REPRODUCIBILITY.md')}"
          f"\n  {zpath} ({os.path.getsize(zpath) / 1e6:.1f} MB)")


if __name__ == "__main__":
    main()
